dependencies:
  - python=3.7
  - pandas=1.0.3
  - rpy2=2.9.4
  - xarray=0.15.0
  - scipy=1.4.1
  - pip=20.0.2
  - pip:
      - netCDF4==1.5.3
      - coverage==5.0.4
      - sphinx==3.0.1
      - sphinx-autodoc-typehints==1.10.3
